name: example
description: Example app for flutter_citizen_printer plugin.
publish_to: 'none'
environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_citizen_printer:
    path: ../
flutter:
  uses-material-design: true
  assets:
    - assets/sample.bmp
